# Generated by Django 5.0.6 on 2024-07-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
