# Generated by Django 5.0.7 on 2024-08-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
