# Generated by Django 5.0.6 on 2024-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='sysLogo')),
                ('image', models.ImageField(blank=True, upload_to='sysimg')),
                ('about', models.TextField(blank=True)),
                ('slogan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'db_table': 'system_system',
                'ordering': ['name'],
            },
        ),
    ]
