# Generated by Django 5.0.6 on 2024-07-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsystem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
