# Generated by Django 5.0.6 on 2024-07-25 14:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_systemsystem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsystem',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='systemsystem',
            name='slogan',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
